-- Write your SQL here

-- Create Database

-- Use Database

-- Create Department Table


CREATE DATABASE COLLEGEDB;
USE COLLEGEDB;
CREATE TABLE DEPARTMENT(DEPARTMENT_ID INT PRIMARY KEY,DEPARTMENT_NAME VARCHAR(100), HOD VARCHAR(100));
DESC DEPARTMENT;
